{{- $appName := "fastapi" -}}

apiVersion: v1
{{- include "coelho-llm-rotator.ServiceSettings" (dict "appName" $appName "root" .) | nindent 0 }}
{{- include "coelho-llm-rotator.ServicePortsSettings" (dict "appName" $appName "root" .) }}
